[package]
name = "windowless"
version = "0.1.0"
edition = "2021"
authors = ["John Nunley <jtnunley01@gmail.com>"]
license = "LGPL-3.0-or-later OR MPL-2.0"

[dependencies]
slotmap = { version = "1.0.6", default-features = false }
smallvec = "1.10.0"
tinyvec = "1.6.0"
